spring.application.name=shadowfit

# [SWAGGER]
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# [HikariCP]
spring.datasource.hikari.initialization-fail-timeout=30000
spring.datasource.hikari.connection-timeout=30000

# [SQL Init & JPA]
# ?? SQL ??? ?? JPA ?? ?? ??? ????? ?????.
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# [DB Connection]
spring.datasource.url=jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# [Logging]
logging.level.root=${LOG_LEVEL_ROOT:INFO}
logging.level.com.Homini.HoPT=${LOG_LEVEL_HOMINI:INFO}

# [JWT]
jwt.secret=${JWT_SECRET}
jwt.expiration_time=${JWT_EXPIRATION_TIME}
jwt.refresh_expiration_time=${JWT_REFRESH_EXPIRATION_TIME}


# [Whitelist]
security.whitelist[0]=/
security.whitelist[1]=/error
security.whitelist[2]=/favicon.ico
security.whitelist[3]=/v3/api-docs
security.whitelist[4]=/v3/api-docs/
security.whitelist[5]=/v3/api-docs/**
security.whitelist[6]=/swagger-ui/**
security.whitelist[7]=/swagger-ui.html
security.whitelist[8]=/api-docs/**
security.whitelist[9]=/swagger-resources/**
security.whitelist[10]=/webjars/**
security.whitelist[11]=/member/login
security.whitelist[12]=/member/signup
security.whitelist[13]=/css/**
security.whitelist[14]=/js/**
security.whitelist[15]=/img/**
security.whitelist[16]=/ws/**